GET http://localhost:3333/courses
###

GET http://localhost:3333/courses/37910873-fe66-4a4c-8977-369de9174899
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOTkyYjg4Zi0yZGZkLTQxN2YtYjNiZC05MDliNmYzMjc2ZDUiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjUyNTEwNH0.j-VBDcT4HfOE3iHvz7umSMmC6UyT7cUS54lTBeRBEX8

###

POST http://localhost:3333/courses/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOTkyYjg4Zi0yZGZkLTQxN2YtYjNiZC05MDliNmYzMjc2ZDUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NjUyNjg1MH0.ZfYG4D0b70aYGi2Y554D6FF3rJc5IE26Z5gDc4Dbj9s
Content-Type: application/json

{
  "title": "Bolas",
  "description": "Hello world"
}

###

PUT http://localhost:3333/courses/
Content-Type: application/json

{
  "id": "bd9d47e2-7200-4160-aec6-f94f325b6699",
  "title": "Curso de Docker Avançado",
  "description": "Hello world"
}

###
DELETE http://localhost:3333/courses/2/

###

POST http://localhost:3333/sessions/
Content-Type: application/json

{
  "email": "jorge123@gmail.com",
  "password": "123123123"
}

###

POST http://localhost:3333/register/
Content-Type: application/json

{
  "name": "jorge",
  "email": "jorge123@gmail.com",
  "password": "123123123"
}